version: '3.8'

services:
  sv-client:
    image: sv-client
    restart: on-failure
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./:/app
      - /app/node_modules
